"""Printable P6 report templates built from supplied P2/P3 and adapter data."""
from __future__ import annotations

from html import escape
from typing import Any, Dict, Iterable

TEMPLATE_VERSION = "P6-1.0"
TITLES = {
    "OIML_R76_2_TYPE_EVALUATION": "OIML R76-2:2007 Type Evaluation Report",
    "GATC_THIRD_SCHEDULE_VERIFICATION": "GATC Third Schedule Verification Certificate",
    "GENERIC_VERIFICATION": "Configurable Verification Record",
    "REJECTION_DOCUMENT": "Notice of Non-Compliance / Rejection Document",
    "TECHNICAL_EVIDENCE_ANNEX": "Technical Evidence Annex",
}


def _text(value: Any) -> str:
    if value is None or value == "": return "Not supplied"
    if isinstance(value, dict): return "Structured data supplied"
    if isinstance(value, (list, tuple, set)): return ", ".join(_text(item) for item in value) or "Not supplied"
    return escape(str(value))


def _table(rows: Iterable[tuple[str, Any]]) -> str:
    return "<table>" + "".join(f"<tr><th>{_text(key)}</th><td>{_text(value)}</td></tr>" for key, value in rows) + "</table>"


def _section(title: str, content: str, style: str = "") -> str:
    return f"<section class='section {style}'><h2>{_text(title)}</h2>{content}</section>"


def _list(items: Any) -> str:
    values = items if isinstance(items, list) else ([] if not items else [items])
    return "<ul>" + "".join(f"<li>{_text(value)}</li>" for value in values) + "</ul>" if values else "<p>Not supplied.</p>"


def _records(report: Dict[str, Any], job: Dict[str, Any]) -> list[tuple[str, Any]]:
    return [("Report number", report.get("report_number")), ("Job ID", report.get("job_id")), ("Job number", job.get("job_number") or report.get("job_number")), ("Generated", report.get("generated_at")), ("Generated by", report.get("generated_by"))]


def _instrument(report: Dict[str, Any], inst: Dict[str, Any]) -> list[tuple[str, Any]]:
    return [("Instrument ID", report.get("instrument_id")), ("Manufacturer", inst.get("manufacturer")), ("Model", inst.get("model_name") or inst.get("model_number")), ("Serial number", report.get("serial_number") or inst.get("serial_number")), ("Accuracy class", inst.get("accuracy_class")), ("Max / Min", f"{_text(inst.get('max_capacity') or inst.get('Max'))} / {_text(inst.get('min_capacity') or inst.get('Min'))}"), ("e / d", f"{_text(inst.get('e'))} / {_text(inst.get('d'))}")]


def _references(report: Dict[str, Any], approval: Dict[str, Any], results: Dict[str, Any]) -> list[tuple[str, Any]]:
    return [("Approval number", report.get("approval_number") or approval.get("approval_number")), ("Regulatory profile", approval.get("regulatory_profile_id")), ("MPE reference", results.get("mpe_reference")), ("MPE information supplied", results.get("mpe_information")), ("References supplied by upstream", ", ".join(approval.get("regulatory_rule_references") or []))]


def _observations(items: Any) -> str:
    rows = items if isinstance(items, list) else []
    if not rows: return "<p>No observations supplied.</p>"
    body = "".join(f"<tr><td>{_text(row.get('observation_id'))}</td><td>{_text(row.get('description'))}</td><td>{_text(row.get('result'))}</td><td>{_text(row.get('data_source'))}</td></tr>" for row in rows)
    return f"<table><thead><tr><th>Observation</th><th>Description</th><th>Result</th><th>Source</th></tr></thead><tbody>{body}</tbody></table>"


def _evidence(context: Dict[str, Any]) -> str:
    rows = context.get("evidence") or []
    if not rows: return "<p>No evidence metadata supplied.</p>"
    body = "".join(f"<tr><td>{_text(row.get('evidence_id'))}</td><td>{_text(row.get('file_name'))}</td><td>{_text(row.get('description'))}</td><td>{_text(row.get('data_source'))}</td></tr>" for row in rows)
    return f"<table><thead><tr><th>Reference</th><th>Attachment</th><th>Description</th><th>Source</th></tr></thead><tbody>{body}</tbody></table>"


def _review(context: Dict[str, Any]) -> list[tuple[str, Any]]:
    reviewer, environment, certificate = context.get("reviewer") or {}, context.get("environment") or {}, context.get("test_weight_certificate") or {}
    return [("Reviewer", reviewer.get("reviewer_name")), ("Review status", reviewer.get("review_status")), ("Environmental record", environment.get("note") or environment.get("data_source")), ("Test-weight / calibration reference", certificate.get("certificate_number")), ("Evidence entries", len(context.get("evidence") or []))]


def _signature() -> str:
    return "<div class='footer'><div>Prepared by: ________________________<br>Signature / reference: ________________________</div><div>Technical review / approval: ________________________<br>Date: ________________________</div></div>"


def _rejection_notice(results: Dict[str, Any]) -> str:
    """Make a rejection notice unmistakable without manufacturing a failure."""
    return (
        "<div class='rejection-notice'><strong>REJECTION / NON-COMPLIANCE NOTICE</strong>"
        f"<br>Recorded workflow outcome: {_text(results.get('outcome'))}. "
        "This notice presents only the information supplied to P6; it does not "
        "assert an unrecorded measured failure.</div>"
    )


def _header(report: Dict[str, Any], title: str, subtitle: str, demo: bool) -> str:
    badge = "DEMO/MOCK DATA PRESENT — NOT A MEASUREMENT RECORD" if demo else "BACKEND-RECORDED REPORT SNAPSHOT"
    return f"<section class='head'><div class='meta'><strong>{_text(report.get('report_number'))}</strong><br>Generated: {_text(report.get('generated_at'))}</div><div><small>METRIQ · NAWI TEST &amp; VERIFICATION MANAGEMENT</small><h1>{_text(title)}</h1><small>{_text(subtitle)}</small></div></section><p><span class='badge {'demo' if demo else ''}'>{_text(badge)}</span></p>"


def _oiml(context: Dict[str, Any]) -> str:
    report, job, inst, approval, results = context["report"], context.get("job", {}), context.get("instrument", {}), context.get("approval", {}), context.get("results", {})
    return "".join([_section("Type Evaluation Identification", _table(_records(report, job) + [("Evaluation status", results.get("outcome"))])), _section("Manufacturer / Model Identification", _table(_instrument(report, inst))), _section("Model Approval / Reference Information", _table(_references(report, approval, results))), _section("Metrological Characteristics", _table(_instrument(report, inst)[4:])), _section("Applicable Test Programme", _list(job.get("applicable_tests"))), _section("Test-Point / Evaluation Matrix", _observations(context.get("observations"))), _section("MPE / Regulatory Reference Information", _table(_references(report, approval, results)[2:])), _section("Observations and Evaluation Outcome", _table([("Recorded outcome", results.get("outcome")), ("Observation source", "Labelled P4 adapter output is currently supplied.")])), _section("Evidence / Traceability", _evidence(context)), _section("Review / Signature", _table(_review(context)) + _signature())])


def _gatc(context: Dict[str, Any]) -> str:
    report, job, inst, approval, results = context["report"], context.get("job", {}), context.get("instrument", {}), context.get("approval", {}), context.get("results", {})
    return "".join([_section("Verification Certificate Identification", _table(_records(report, job) + [("Certificate status", report.get("status"))])), _section("Instrument Particulars", _table(_instrument(report, inst))), _section("Model Approval Reference", _table(_references(report, approval, results)[:2])), _section("GATC / Statutory Routing Reference", _table([("GATC reference", approval.get("gatc_reference")), ("Testing centre", job.get("testing_centre_name")), ("Job routing", job.get("routing_decision"))])), _section("Verification Test Plan", _list(job.get("applicable_tests"))), _section("Verification Results", _observations(context.get("observations"))), _section("MPE / Tolerance References", _table(_references(report, approval, results)[2:])), _section("Inspector / Testing-Centre Information", _table([("Inspector", job.get("assigned_inspector_name")), ("Testing centre", job.get("testing_centre_name")), ("Job status", job.get("status"))])), _section("Decision / Status", _table([("Recorded decision", results.get("outcome")), ("Report status", report.get("status"))])), _section("Evidence / Reviewer", _evidence(context) + _table(_review(context))), _section("Certificate / Signature Area", _signature())])


def _generic(context: Dict[str, Any]) -> str:
    report, job, inst, approval, results = context["report"], context.get("job", {}), context.get("instrument", {}), context.get("approval", {}), context.get("results", {})
    return "".join([_section("Configurable Verification Record", _table(_records(report, job) + [("Report status", report.get("status"))])), _section("Instrument Particulars", _table(_instrument(report, inst))), _section("Applicable State / Regulatory Profile", _table(_references(report, approval, results)[:2] + [("Upstream references", ", ".join(approval.get("regulatory_rule_references") or []))])), _section("Test Programme", _list(job.get("applicable_tests"))), _section("Results and Tolerance Comparison", _observations(context.get("observations")) + _table(_references(report, approval, results)[2:4])), _section("Decision", _table([("Recorded outcome", results.get("outcome")), ("Configurable record", "Not represented as one specific state's statutory form.")])), _section("Evidence", _evidence(context)), _section("Reviewer / Signature", _table(_review(context)) + _signature())])


def _rejection(context: Dict[str, Any]) -> str:
    report, job, inst, approval, results = context["report"], context.get("job", {}), context.get("instrument", {}), context.get("approval", {}), context.get("results", {})
    return "".join([_rejection_notice(results), _section("Notice Identification", _table(_records(report, job) + [("Notice status", "REJECTION / NON-COMPLIANCE")]), "rejection"), _section("Instrument / Job Particulars", _table(_instrument(report, inst) + [("Job status", job.get("status"))])), _section("Test Programme", _list(job.get("applicable_tests"))), _section("Rejection Decision", _table([("Recorded decision", results.get("outcome")), ("Report status", report.get("status"))]), "rejection"), _section("Failed / Non-Compliant Criteria", "<p>No unlabelled failure is asserted. Available adapter observations are listed below.</p>" + _observations(context.get("observations")), "rejection"), _section("Observed / Result Information", _table([("Observation source", "Labelled P4 adapter output is currently supplied."), ("Recorded outcome", results.get("outcome"))])), _section("Applicable MPE / Reference Information", _table(_references(report, approval, results)[2:])), _section("Reason for Rejection", _table([("Available reason", job.get("notes") or "Not supplied by upstream workflow.")])), _section("Required Corrective / Retest Action", "<p>Corrective action and retest requirements must be supplied by the responsible workflow; this template does not invent them.</p>"), _section("Reviewer / Authority", _table(_review(context))), _section("Evidence / Traceability", _evidence(context)), _section("Notice / Signature Area", _signature(), "rejection")])


def _annex(context: Dict[str, Any]) -> str:
    report, job, inst = context["report"], context.get("job", {}), context.get("instrument", {})
    environment, certificate, results, approval = context.get("environment") or {}, context.get("test_weight_certificate") or {}, context.get("results", {}), context.get("approval", {})
    return "".join([_section("Annex Identification", _table(_records(report, job) + [("Parent report / job reference", report.get("report_number") or job.get("job_number"))])), _section("Instrument Identification", _table(_instrument(report, inst))), _section("Evidence Index", _evidence(context)), _section("Observation References", _observations(context.get("observations"))), _section("Environmental Records", _table([("Temperature", environment.get("temperature")), ("Humidity", environment.get("humidity")), ("Record note", environment.get("note")), ("Source", environment.get("data_source"))])), _section("Test-Weight / Calibration Certificate References", _table([("Certificate number", certificate.get("certificate_number")), ("Reference note", certificate.get("note")), ("Source", certificate.get("data_source"))])), _section("Reviewer / Evidence Metadata", _table(_review(context))), _section("Traceability / Audit Information", _table([("Job state-history entries", len(job.get("state_history") or [])), ("Applicable tests", ", ".join(job.get("applicable_tests") or [])), ("MPE reference", results.get("mpe_reference")), ("MPE information supplied", results.get("mpe_information"))])), _section("Attachment / Reference Section", "<p>Attachment references above are metadata only. Any DEMO/MOCK entry is not a measured, reviewed, or issued record.</p>")])


def render_report_html(context: Dict[str, Any]) -> str:
    """Render a self-contained, type-specific browser-printable report."""
    report = context["report"]
    report_type = str(report.get("report_type"))
    title = TITLES.get(report_type, report_type.replace("_", " "))
    bodies = {"OIML_R76_2_TYPE_EVALUATION": _oiml, "GATC_THIRD_SCHEDULE_VERIFICATION": _gatc, "GENERIC_VERIFICATION": _generic, "REJECTION_DOCUMENT": _rejection, "TECHNICAL_EVIDENCE_ANNEX": _annex}
    subtitles = {"OIML_R76_2_TYPE_EVALUATION": "Practice/demo type-evaluation template only; it is not an official issued OIML certificate.", "GATC_THIRD_SCHEDULE_VERIFICATION": "Practice/demo verification template based only on supplied P2/P3 and adapter data; it is not an official issued statutory certificate.", "GENERIC_VERIFICATION": "Configurable verification structure; not represented as one specific state's statutory form.", "REJECTION_DOCUMENT": "Backend-recorded notice layout; no measured failure is asserted beyond supplied data.", "TECHNICAL_EVIDENCE_ANNEX": "Supporting evidence attachment/index; it is not a certificate."}
    body = bodies.get(report_type, _generic)(context)
    return f"""<!doctype html><html><head><meta charset='utf-8'><title>{_text(report.get('report_number'))}</title><style>@page{{size:A4;margin:16mm}}body{{font:12px Arial,sans-serif;color:#182b3c;line-height:1.4}}.head{{border-bottom:3px solid #174d70;padding-bottom:12px}}h1{{font-size:21px;margin:5px 0}}h2{{font-size:14px;margin:22px 0 8px;color:#174d70}}.meta{{float:right;text-align:right}}table{{width:100%;border-collapse:collapse;margin:6px 0}}th,td{{padding:7px 8px;border:1px solid #c9d5df;text-align:left;vertical-align:top}}th{{width:32%;background:#eff5f8}}.badge{{display:inline-block;padding:6px 9px;font-weight:bold;border:1px solid #47677c}}.demo{{background:#fff3cd;color:#765300}}.section{{break-inside:avoid}}.rejection h2{{color:#8b1e1e}}.rejection th{{background:#fde8e8}}.rejection-notice{{border:2px solid #8b1e1e;background:#fde8e8;color:#721c24;padding:12px;font-size:14px;line-height:1.5}}.footer{{margin-top:30px;border-top:1px solid #9fb3c1;padding-top:14px;display:flex;justify-content:space-between}}ul{{margin:6px 0;padding-left:18px}}</style></head><body>{_header(report, title, subtitles.get(report_type, 'Backend-generated report snapshot.'), bool(context.get('contains_demo_data')))}{body}</body></html>"""
